name: gaudi
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    - colorlog==6.8.0
    - datasets==2.16.1
    - einops==0.7.0
    - fvcore==0.1.5.post20221221
    - hydra-colorlog==1.2.0
    - hydra-core==1.3.2
    - hydra-optuna-sweeper==1.2.0
    - lightning==2.1.3
    - lightning-bolts==0.7.0
    - lightning-utilities==0.10.1
    - numba==0.58.1
    - nvidia-dali-cuda120==1.33.0
    - omegaconf==2.3.0
    - python-dotenv==1.0.0
    - rootutils==1.0.7
    - timm==0.9.12
    - torchmetrics==1.3.0.post0
    - transformers==4.37.0
    - wandb==0.16.2
variables:
  PROJECT_ROOT: $PWD
