_target_: src.models.layers.mlp.MlpCustom
linear1_cfg:
  _target_: src.models.layers.kernelized.Kernelized
  rank: 0.5
  kernel_cfg:
    _target_: src.models.layers.kernelized.HLapKernel
linear2_cfg: ${.linear1_cfg}

