_target_: src.models.mlp_mixer.MlpMixer
defaults:
  - token_mlp_cfg: null
  - channel_mlp_cfg: null
patch_size: 4
num_blocks: 8
img_size: 32
embed_dim: 512
drop_rate: 0.0
drop_path_rate: 0.1
mlp_ratio: [0.5, 4.0]
